# Generated by Django 5.2.14 on 2026-05-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('appointments', '0002_alter_appointment_scheduled_at'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(verbose_name='Triệu chứng')),
                ('diagnosis', models.TextField(verbose_name='Chẩn đoán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.patient')),
            ],
            options={
                'verbose_name': 'Hồ sơ bệnh án',
                'verbose_name_plural': 'Hồ sơ bệnh án',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, verbose_name='Hướng dẫn dùng thuốc')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_dispensed', models.BooleanField(default=False, verbose_name='Đã cấp thuốc')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='medical_records.medicalrecord')),
            ],
            options={
                'verbose_name': 'Đơn thuốc',
                'verbose_name_plural': 'Đơn thuốc',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('dosage', models.CharField(max_length=200, verbose_name='Liều dùng')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Số ngày dùng')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Ghi chú')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='pharmacy.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical_records.prescription')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn thuốc',
                'verbose_name_plural': 'Chi tiết đơn thuốc',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200, verbose_name='Tên xét nghiệm')),
                ('result', models.TextField(verbose_name='Kết quả')),
                ('normal_range', models.CharField(blank=True, max_length=100, verbose_name='Chỉ số bình thường')),
                ('image', models.ImageField(blank=True, null=True, upload_to='test_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='medical_records.medicalrecord')),
            ],
            options={
                'verbose_name': 'Kết quả xét nghiệm',
                'verbose_name_plural': 'Kết quả xét nghiệm',
            },
        ),
    ]
