# Generated by Django 5.2.14 on 2026-05-16 03:47

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Danh mục thuốc',
                'verbose_name_plural': 'Danh mục thuốc',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Tên thuốc')),
                ('ingredient', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hoạt chất')),
                ('unit', models.CharField(choices=[('vien', 'Viên'), ('chai', 'Chai'), ('hop', 'Hộp'), ('ong', 'Ống'), ('goi', 'Gói'), ('ml', 'ml'), ('mg', 'mg')], max_length=10, verbose_name='Đơn vị')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='pharmacy.category')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Danh mục thuốc',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('min_quantity', models.PositiveIntegerField(default=10, verbose_name='Số lượng tối thiểu')),
                ('expiry_date', models.DateField(verbose_name='Hạn sử dụng')),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pharmacy.medicine')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Quản lý tồn kho',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Hướng dẫn dùng thuốc chung')),
                ('is_dispensed', models.BooleanField(default=False, verbose_name='Đã cấp thuốc')),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.medicalrecord')),
            ],
            options={
                'verbose_name': 'Đơn thuốc',
                'verbose_name_plural': 'Đơn thuốc',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('dosage', models.CharField(max_length=200, verbose_name='Liều dùng')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Số ngày dùng')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='pharmacy.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn thuốc',
                'verbose_name_plural': 'Chi tiết đơn thuốc',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho'), ('adjust', 'Điều chỉnh')], max_length=10)),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pharmacy.medicine')),
            ],
            options={
                'verbose_name': 'Giao dịch kho',
                'verbose_name_plural': 'Lịch sử giao dịch kho',
                'ordering': ['-created_date'],
            },
        ),
    ]
