# Generated by Django 5.2.14 on 2026-05-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Danh mục thuốc',
                'verbose_name_plural': 'Danh mục thuốc',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên thuốc')),
                ('unit', models.CharField(choices=[('vien', 'Viên'), ('chai', 'Chai'), ('hop', 'Hộp'), ('ong', 'Ống'), ('goi', 'Gói'), ('ml', 'ml'), ('mg', 'mg')], max_length=10, verbose_name='Đơn vị')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='pharmacy.category')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Danh mục thuốc',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('min_quantity', models.PositiveIntegerField(default=10, verbose_name='Số lượng tối thiểu')),
                ('expiry_date', models.DateField(verbose_name='Hạn sử dụng')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pharmacy.medicine')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Quản lý tồn kho',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho'), ('adjust', 'Điều chỉnh')], max_length=10)),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pharmacy.medicine')),
            ],
            options={
                'verbose_name': 'Giao dịch kho',
                'verbose_name_plural': 'Lịch sử giao dịch kho',
            },
        ),
    ]
