# Generated by Django 5.2.14 on 2026-05-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reminder', 'Nhắc lịch hẹn'), ('confirmed', 'Lịch hẹn được xác nhận'), ('cancelled', 'Thông báo huỷ'), ('result', 'Kết quả xét nghiệm'), ('follow_up', 'Nhắc tái khám'), ('prescription', 'Đơn thuốc mới'), ('invoice', 'Hóa đơn mới'), ('general', 'Chung')], default='general', max_length=20),
        ),
    ]
