# Generated by Django 5.2.14 on 2026-05-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='temperature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
