# Generated by Django 5.2.14 on 2026-05-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(),
        ),
    ]
