# Generated by Django 5.2.14 on 2026-05-16 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('revenue', 'Doanh thu'), ('patient', 'Bệnh nhân'), ('disease', 'Bệnh phổ biến'), ('service', 'Dịch vụ'), ('inventory', 'Tồn kho')], max_length=20, verbose_name='Loại báo cáo')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('date_from', models.DateField(verbose_name='Từ ngày')),
                ('date_to', models.DateField(verbose_name='Đến ngày')),
                ('data_snapshot', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu snapshot')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Báo cáo thống kê',
                'ordering': ['-created_date'],
            },
        ),
    ]
