# Generated by Django 5.2.14 on 2026-05-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.AlterField(
            model_name='report',
            name='data_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('revenue', 'Doanh thu'), ('patient', 'Bệnh nhân'), ('disease', 'Bệnh phổ biến'), ('service', 'Dịch vụ'), ('inventory', 'Tồn kho')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
