# Generated by Django 5.2.14 on 2026-05-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_avatar_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Bệnh nhân'), ('doctor', 'Bác sĩ'), ('staff', 'Nhân viên'), ('pharmacy', 'Dược sĩ'), ('admin', 'Quản trị viên')], default='patient', max_length=20),
        ),
    ]
