# Generated by Django 5.2.14 on 2026-05-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, null=True),
        ),
    ]
