# Generated by Django 5.2.14 on 2026-05-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='full_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(related_name='doctors', to='accounts.specialty'),
        ),
    ]
