# Generated by Django 5.2.14 on 2026-05-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_doctor_specialty_remove_patient_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
