# Generated by Django 5.2.14 on 2026-05-22 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_options_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(choices=[('momo', 'Ví điện tử MoMo'), ('vnpay', 'Cổng thanh toán VNPAY')], max_length=10)),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='Mã đơn hàng hệ thống')),
                ('transaction_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch đối tác')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Đang xử lý'), ('success', 'Thành công'), ('failed', 'Thất bại')], default='pending', max_length=10)),
                ('response_data', models.TextField(blank=True, null=True, verbose_name='Dữ liệu phản hồi thô')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_trackings', to='billing.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
